.github/workflows/build-and-analyze.yml
if check for workflow imrpoved to also run on push to master / workflow dispatch
=> Better if check for build and analyze

src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, src/jwtcookie/Authentication/Altinn.Common.Authentication.sln, src/jwtcookie/Authentication/Constants/AltinnCoreClaimTypes.cs, src/jwtcookie/Authentication/Constants/KeyVaultSettings.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookieDefaults.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookieEvents.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookieExtensions.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookieFailedContext.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookieHandler.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookieOptions.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookiePostConfigureOptions.cs, src/jwtcookie/Authentication/JwtCookie/JwtCookieValidatedContext.cs, src/jwtcookie/Authentication/Utils/JwtTokenUtil.cs
…authentication repo.
- #187-Add support for maskinporten token in JWTOCookie package
=> Moved Common.Authentication from altinn-studio repo to altinn-authentication

.github/workflows/build-and-analyze-fork.yml, .github/workflows/build-and-analyze.yml, .github/workflows/codeql-analysis.yml, Dockerfile, README.md, src/Authentication/Altinn.Platform.Authentication.csproj, src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj
Update .Net framework from 6.0 to 7.0
-altinn-authorization #181
=> Update .net version

src/Authentication/Altinn.Platform.Authentication.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/AuthenticationControllerTests.cs
=> PAtched jwtcookie and updated test

src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, src/jwtcookie/Authentication/JwtCookie/JwtCookieHandler.cs, src/jwtcookie/Authentication/Utils/ConfigurationMangerUtil.cs
Fix for configurationmanager reuse
=> Fixed singleton for configurationmanager

src/Authentication/Controllers/AuthenticationController.cs, test/Altinn.Platform.Authentication.Tests/Controllers/AuthenticationControllerTests.cs
Added support for new ACR values
Fix for https://github.com/Altinn/altinn-authentication/issues/176
=> Fixed support for new id porten claims for auth level

src/Authentication/Altinn.Platform.Authentication.csproj, src/Authentication/Controllers/AuthenticationController.cs, src/Authentication/Program.cs, test/Altinn.Platform.Authentication.Tests/Controllers/AuthenticationControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/LogoutControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Fakes/SigningKeyResolverStub.cs
Updates to access token 2.0 with fixes for breaking changes
=> Updates to access token 2.0 with fixes for breaking changes

src/Authentication/Clients/EventsQueueClient.cs, src/Authentication/Controllers/AuthenticationController.cs, src/Authentication/Controllers/LogoutController.cs, src/Authentication/Enum/AuthenticationEventType.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Authentication/Helpers/EventlogHelper.cs, src/Authentication/Model/UserAuthenticationModel.cs, src/Authentication/Services/EventLogService.cs, test/Altinn.Platform.Authentication.Tests/Controllers/LogoutControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Utils/PrincipalUtil.cs
=> Implemented event logging for logout operation

src/Authentication/Helpers/EventlogHelper.cs
=> Added 1 more header possibility for ipadress

src/Authentication/Enum/AuthenticationEventType.cs, src/Authentication/Enum/AuthenticationMethod.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Authentication/Helpers/EventlogHelper.cs, src/Authentication/Model/AuthenticationEvent.cs, test/Altinn.Platform.Authentication.Tests/Controllers/AuthenticationControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/LogoutControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Services/EventLogServiceTest.cs
- Added enum to the authentication event model instead og string
- Updated enums for authenticationmethod and authenticationeventtype
- Updated mapping of authentication level for idporten
- Upadted eventlog helper with enum mapping instead of string
- Removed TimeToDelete
- Updated unit tests
- https://github.com/Altinn/altinn-auth-audit-log/issues/40
=> Updated the model and corresponding services for the event log

src/Authentication/Helpers/EventlogHelper.cs
=> Change the x-forwarded-for header to lowercase

src/Authentication/Altinn.Platform.Authentication.csproj, src/Persistance/Altinn.Platform.Authentication.Persistance.csproj, src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj
=> update from main

src/Authentication/Altinn.Platform.Authentication.csproj, src/Persistance/Altinn.Platform.Authentication.Persistance.csproj, src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj
=> chore: update from main

src/Authentication/Enum/AuthenticationMethod.cs, src/Authentication/Helpers/AuthenticationHelper.cs
Synced authenticationmethod enum with Altinn2 and added Altinn3 specific enums
=> Synced authenticationmethod enum

src/Authentication/Services/SystemRegisterService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/RepositoryInterfaces/ISystemUserRepository.cs, src/Persistance/RepositoryImplementations/SystemUserRepository.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Mocks/SystemUserServiceMock.cs
Moved SystemUserService Mocklist to the proper place as a SystemUserServiceMock,
wrote a proper SystemUserService class to call the Repository
Started writing Automatic tests for SystemRegister Controller and Db
More to come in the same theme, but trying to keep the PR smallish.
=> Tests for SystemRegister 

.github/workflows/build-and-analyze-fork.yml, .github/workflows/build-and-analyze.yml, .github/workflows/codeql-analysis.yml, Dockerfile, README.md, src/Authentication/Altinn.Platform.Authentication.csproj, src/Authentication/Enum/AuthenticationMethod.cs, src/Authentication/Helpers/EventlogHelper.cs, src/Authentication/Model/AuthenticationEvent.cs, src/Authentication/Model/KeyVaultSettings.cs, src/Authentication/Program.cs, src/Authentication/Services/EventLogService.cs, src/Authentication/Services/JwtSigningCertificateProvider.cs, src/Core/Altinn.Platform.Authentication.Core.csproj, src/Persistance/Altinn.Platform.Authentication.Persistance.csproj, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/AuthenticationControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/LogoutControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Fakes/JwtSigningCertificateProviderStub.cs, test/Altinn.Platform.Authentication.Tests/Services/EventLogServiceTest.cs
=> Updated datetime for authenticationevent to utc

.github/workflows/publish-jwtcookie-nuget.yml
=> Action to publish nuget package for JWTCookieAuthentication

Dockerfile
=> Update Dockerfile for pg migration

src/Authentication/Controllers/SystemUserController.cs
=> test av migration script og idporten åpning til endepunkt

Dockerfile, src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Program.cs
=> Sr fix broken deploy

src/Authentication/Controllers/SystemUserController.cs, src/Authentication/appsettings.Development.json, src/Authentication/appsettings.json, test/Altinn.Platform.Authentication.Tests/RepositoryDataAccess/DbFixture.cs
=> Sr simple test maskinporten

src/Authentication/Controllers/SystemUserController.cs, src/Core/Models/SystemUser.cs
=> Sr system user jsonfix

src/Authentication/Controllers/SystemUserController.cs, src/Persistance/Extensions/PersistanceDependencyInjection.cs
=> Sr quickfix postgres di

src/Authentication/Controllers/SystemUserController.cs
=> removed authorize from system user

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Services/Interfaces/ISystemRegisterService.cs, src/Authentication/Services/SystemRegisterService.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/MockData/SystemRegister.json, test/Altinn.Platform.Authentication.Tests/Mocks/SystemRegisterServiceMock.cs, test/Altinn.Platform.Authentication.Tests/Utils/AssertionUtil.cs
=> added unit tests, get endpoint for system

.github/containerscan/allowedlist.yaml, src/Authentication/Services/SystemRegisterService.cs, src/Core/Models/Right.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Mocks/SystemRegisterServiceMock.cs, test/Altinn.Platform.Authentication.Tests/RepositoryDataAccess/SystemRegisterRepositoryDbTests.cs, test/Altinn.Platform.Authentication.Tests/RepositoryDataAccess/SystemUserRepositoryDbTests.cs
Renamed resources to resource to give more correct name
=> Fixed resources to resource to match access management

src/Authentication/Controllers/SystemRegisterController.cs, src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs
=> fixed select query for checking existing clientids

src/Authentication/Program.cs, src/Authentication/appsettings.Development.json, src/Authentication/appsettings.json
added config of PlatformSettings
bug in at env
=> PlatformSettings

src/Authentication/Controllers/SystemRegisterController.cs
=> Fixed policy scope for system register

src/Persistance/RepositoryImplementations/RequestRepository.cs
=> fix syntax error in update status in request repository

src/Authentication/Services/RequestSystemUserService.cs, src/Core/RepositoryInterfaces/IRequestRepository.cs, src/Persistance/RepositoryImplementations/RequestRepository.cs
=> set up systemuser id after system user creation

src/Authentication/Controllers/RequestSystemUserController.cs, src/Authentication/Services/Interfaces/IRequestSystemUser.cs, src/Authentication/Services/RequestSystemUserService.cs, src/Core/RepositoryInterfaces/IRequestRepository.cs, src/Persistance/RepositoryImplementations/RequestRepository.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs
=> Added endpoint for rejecting system request

src/Authentication/Controllers/RequestSystemUserController.cs
=> Fixed comments on service

src/Authentication/Altinn.Platform.Authentication.csproj, src/Persistance/Altinn.Platform.Authentication.Persistance.csproj
=> dependabot bumps manually

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Authentication/Model/ConsumerClaim.cs, src/Core/Constants/AuthzConstants.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs
=> Validation for system owner/admin scope

src/Authentication/Program.cs, src/Core/Constants/AuthzConstants.cs
=> updated scopes and policynaming

.github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/task.md
Added issue-temples copied from Tilgangsstyring
Templates for Epic, feature, task
=> added issue-templates

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Core/Models/OrgClaim.cs, src/Core/Models/SystemRegisterRequest.cs, src/Core/Models/VendorInfo.cs, src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs
=> Updated the type of vendor

src/Authentication/Controllers/SystemRegisterController.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs
=> Add validation for existing system id

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegister.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegister01.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterInvalidSystemIdFormat.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterUpdateInvalid.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterUpdateRequest.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterUpdateResponse.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterWithoutRight.json
=> added check for systemid format and updated tests and test data

src/Authentication/Altinn.Platform.Authentication.csproj, src/Authentication/Controllers/RequestSystemUserController.cs, src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Model/Base64UrlEncoder.cs, src/Authentication/Model/ListObject.cs, src/Authentication/Model/Opaque.cs, src/Authentication/Model/Paginated.cs, src/Authentication/Services/Interfaces/IRequestSystemUser.cs, src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/RequestSystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/Models/Optional.cs, src/Core/Models/Page.cs, src/Core/RepositoryInterfaces/ISystemUserRepository.cs, src/Persistance/RepositoryImplementations/SystemUserRepository.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Mocks/SystemUserServiceMock.cs
Pagination on 
The following classes are copied from the Resource Registry and have been through a Review already:
- #586
=> Pagination request systemuser

test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs
=> fix broken tests

src/Authentication/Controllers/RequestSystemUserController.cs, src/Authentication/Program.cs, src/Core/Constants/AuthzConstants.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs
=> Added scopes for system user request

src/Integration/Clients/PartiesClient.cs
=> FIxed register url

src/Integration/Clients/PartiesClient.cs
=> add the accesstoken to the client call to register

src/Core/Models/ResourceRegistry/ResourceType.cs
=> Updated resourcetype to match resourceregistry

Dockerfile
=> revert the .net version in docker file

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Authentication/Services/Interfaces/ISystemRegisterService.cs, src/Authentication/Services/RequestSystemUserService.cs, src/Authentication/Services/SystemRegisterService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/Models/Parties/OrganisationNumber.cs, src/Core/Models/SystemRegisters/RegisteredSystem.cs, src/Core/RepositoryInterfaces/ISystemRegisterRepository.cs, src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterResponse.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterUpdateResponse.json, test/Altinn.Platform.Authentication.Tests/Utils/AssertionUtil.cs
=> Systemregister model unification

src/Authentication/Altinn.Platform.Authentication.csproj, src/Authentication/Program.cs, src/Authentication/appsettings.Development.json, test/Altinn.Platform.Authentication.Tests/Utils/TestTokenUtil.cs, test/Altinn.Platform.Authentication.Tests/appsettings.json
Added config for JwtCookie authentiation to support Maskinporten token
=> Added OIDC provider

src/Authentication/Controllers/SystemRegisterController.cs
=> Return RegisteredSystemDTO in GET list of systems

src/Authentication/appsettings.Development.json, src/Authentication/appsettings.json, src/Persistance/RepositoryImplementations/RequestRepository.cs
=> Archiver datetime fix

src/Authentication/Services/RequestSystemUserService.cs
fix bug in https://github.com/Altinn/altinn-authentication/issues/574
- #574
=> validation of redirectUrls in RequestAPI fix

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Authentication/Services/Interfaces/ISystemRegisterService.cs, src/Authentication/Services/SystemRegisterService.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterDtoResponse.json, test/Altinn.Platform.Authentication.Tests/Utils/AssertionUtil.cs
- Add utility method to map RegisteredSystem object to RegisteredSystemDto
- Use new utility method in SystemRegisterController
- this PR
=> Return orgNo without prefix in requests called by bff

src/Authentication/Clients/EventsQueueClient.cs, src/Authentication/Configuration/QueueStorageSettings.cs, src/Authentication/appsettings.json
=> Set timetolive for the authentication event queue message

src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Program.cs, src/Core/Constants/AuthzConstants.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs
=> Added scope check

src/Authentication/Services/ChangeRequestSystemUserService.cs
=> log for test

.github/workflows/scheduled-e2e.yml
=> typo in workflow - workflow failed

src/Authentication/Services/SystemUserService.cs
=> comment revoke until AM supports it

src/Authentication/Services/ChangeRequestSystemUserService.cs, test/Altinn.Platform.Authentication.Tests/Controllers/ChangeRequestControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs
Added the SystemUserId to the ChangeRequest Response model
(it was missing !)
- Manually reported by @Nyeng
=> systemuserId added to response model

src/Authentication/Services/Interfaces/ISystemRegisterService.cs, src/Persistance/Migration/v0.10/01-alter-maskinporten_client.sql, src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs
Removed is_deleted from maskinporten_client and added delete statement to remove the clientid
=> Update delete clientid process

.github/workflows/build-and-analyze-fork.yml, .github/workflows/build-and-analyze.yml, .github/workflows/codeql-analysis.yml, .github/workflows/publish-jwtcookie-nuget.yml, .github/workflows/scheduled-e2e.yml, .github/workflows/system-integration-tests.yml, Dockerfile, README.md, src/Authentication/Altinn.Platform.Authentication.csproj, src/Core/Altinn.Platform.Authentication.Core.csproj, src/Integration/Altinn.Platform.Authentication.Integration.csproj, src/Persistance/Altinn.Platform.Authentication.Persistance.csproj, src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, test/Altinn.Platform.Authentication.SystemIntegrationTests/Altinn.Platform.Authentication.SystemIntegrationTests.csproj, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj
=> Update to .net 9.0

.github/workflows/build-and-analyze-fork.yml
=> duplicate test command flags

test/Altinn.Platform.Authentication.SystemIntegrationTests/Tests/SystemRegisterTests.cs
=> don't delete system register systems you dont have control over

src/Authentication/Configuration/GeneralSettings.cs, src/Authentication/Controllers/AuthenticationController.cs, src/Authentication/appsettings.json, test/Altinn.Platform.Authentication.Tests/Controllers/AuthenticationControllerTests.cs, test/Altinn.Platform.Authentication.Tests/appsettings.json
=> First checkin partner validation

src/Authentication/Controllers/AuthenticationController.cs
always try them if they are there for any exception
=> only try the alternative signingkeys if they where found in the config.

src/Core/Exceptions/DelegationException.cs, src/Core/Models/Rights/AttributeMatchExternal.cs, src/Core/Models/Rights/DelegationStatusExternal.cs, src/Core/Models/Rights/RightDelegationResultExternal.cs, src/Core/Models/Rights/RightsDelegationResponseExternal.cs, src/Integration/AccessManagement/AccessManagementClient.cs
added customexception and log the delegation request and prblem detail for debugging
=> Logging and refactoring for debugging delegation

src/Integration/AccessManagement/AccessManagementClient.cs
=> remove ensuresuccesscode to get the badrequest

src/Integration/AccessManagement/AccessManagementClient.cs
=> fix error logging

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/DelegationHelper.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Helpers/DelegationHelperTests.cs
=> Update get rights to return app in old format

src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/Problems/Problem.cs
=> uncomment the code to revoke rights

src/Integration/AccessManagement/AccessManagementClient.cs
=> removed log information on request

src/Authentication/Controllers/RequestSystemUserController.cs
Fix a bug where an existing request have timedout, but not been deleted and moved to the archive yet.
- #1029
=> Timed Out Status fix

src/Authentication/Services/SystemUserService.cs
=> Update app format to match access management

test/Altinn.Platform.Authentication.SystemIntegrationTests/Resources/Testdata/Systemregister/UnitTestFilePut.json, test/Altinn.Platform.Authentication.SystemIntegrationTests/Tests/SystemRegisterTests.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Tests/SystemUserTests.cs
=> working testdata in tt02

src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, src/jwtcookie/Authentication/Constants/AltinnCoreClaimTypes.cs
=> Added claim

src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj
=> Upgrading 4.0.3

src/Authentication/Controllers/RequestSystemUserController.cs, src/Authentication/Program.cs, src/Core/Constants/AuthzConstants.cs, test/Altinn.Platform.Authentication.Tests/Controllers/ChangeRequestControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Utils/PrincipalUtil.cs
added portal scope as requirement for approve api
=> added portal scope as requirement for approve api

src/jwtcookie/Authentication/Altinn.Common.Authentication.csproj, src/jwtcookie/Authentication/Constants/AltinnCoreClaimTypes.cs
=> Fixed correct urn

test/Altinn.Platform.Authentication.SystemIntegrationTests/Clients/PlatformAuthenticationClient.cs
=> new scopes required for approving requests

test/Altinn.Platform.Authentication.SystemIntegrationTests/Clients/SystemUserClient.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Tests/SystemUserTests.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Utils/UrlConstants.cs
https://github.com/Altinn/altinn-authentication/issues/1074
=> Created test for /PUT Systemuser and reported bug for it #1074

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Core/Models/AccessPackages/AccessPackage.cs, src/Core/Models/SystemRegisters/RegisteredSystem.cs, src/Core/Models/SystemRegisters/RegisteredSystemDTO.cs, src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterWithAccessPackageNull.json
=> Fix null value for accesspackages

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Services/Interfaces/ISystemRegisterService.cs, src/Authentication/Services/SystemRegisterService.cs, src/Authentication/appsettings.json, src/Core/Models/AccessPackages/Package.cs, src/Integration/AccessManagement/AccessManagementClient.cs, src/Integration/AccessManagement/IAccessManagementClient.cs, src/Integration/Altinn.Platform.Authentication.Integration.csproj, src/Integration/MockData/packages.json, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Data/Packages/packages.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterDuplicateAccessPackage.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterInvalidAccessPackage.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterUpdateBadRequest.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterUpdateRequest.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterWithAccessPackage.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/UpdateAccessPackageDuplicate.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/UpdateAccessPackages.json, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs
Added mockdata for accesspackages ,validation for access packages and unit test for the validation
=> Access Package validation

src/Authentication/Helpers/AuthenticationHelper.cs, src/Authentication/Services/RequestSystemUserService.cs, src/Authentication/Services/SystemUserService.cs, test/Altinn.Platform.Authentication.Tests/AuthenticationHelperTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs
=> Fix redirecturl validation

src/Authentication/Controllers/RequestSystemUserController.cs
=> improved the summary headers for the agent requests

src/Authentication/Controllers/ChangeRequestSystemUserController.cs, src/Authentication/Controllers/RequestSystemUserController.cs
- Return full url to new system user GUI for systemuser request confirmUrl and change request confirmUrl 
- #1053
=> Change confirmUrl for systemuser request and change request to use url to new UI

src/Authentication/Controllers/RequestSystemUserController.cs
Use url to new frontend for agent request confirmUrl
- this PR
=> Fix agent request confirmUrl

src/Authentication/Controllers/RequestSystemUserController.cs, src/Authentication/Services/Interfaces/IRequestSystemUser.cs, src/Authentication/Services/RequestSystemUserService.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Mocks/RequestSystemUserServiceMock.cs
=> L5 get agentrequest for bff by party and

src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/Models/SystemUsers/SystemUserRegisterDTO.cs, src/Core/RepositoryInterfaces/ISystemUserRepository.cs, src/Persistance/RepositoryImplementations/SystemUserRepository.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs
=> L5 agent systemuser endpoint for bff

src/Persistance/RepositoryImplementations/SystemUserRepository.cs
=> isbnull check added

src/Authentication/Helpers/AuthenticationHelper.cs, src/Core/Problems/Problem.cs, test/Altinn.Platform.Authentication.Tests/AuthenticationHelperTests.cs
fix redirecturl validation when the allowedredirecturl is listed with queryparams
=> Redirect url validation

src/Integration/MockData/packages.json
- Access packages for client delegation should be in mock so we can create systems in system register with these access packages
- this PR
=> Add access packages for client delegation to mock

src/Authentication/Services/RequestSystemUserService.cs, src/Core/Enums/SystemUserType.cs, src/Core/Models/SystemRegisters/RegisteredSystemDTO.cs, src/Core/Problems/Problem.cs, src/Persistance/Extensions/NpgSqlExtensions.cs, src/Persistance/Extensions/PersistanceDependencyInjection.cs, src/Persistance/Migration/v0.19/01-alter-systemuserprofile-table.sql, src/Persistance/RepositoryImplementations/RequestRepository.cs, src/Persistance/RepositoryImplementations/SystemUserRepository.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs
=> L5 fix systemusertype enum

src/Integration/AccessManagement/AccessManagementClient.cs
=> agent in lowercase

Dockerfile
=> Remove the mockdata for package

src/Core/Models/SystemUsers/AgentDelegationRequest.cs, src/Integration/AccessManagement/AccessManagementClient.cs
=> match the AM delegation model

src/Authentication/Services/SystemRegisterService.cs
=> send only the urnvalue not the whole urn format for accesspackage

src/Integration/AccessManagement/AccessManagementClient.cs
=> fix the getaccesspackage url for AM

src/Authentication/Services/SystemUserService.cs, src/Core/Models/SystemUsers/DelegationResponse.cs, src/Integration/AccessManagement/AccessManagementClient.cs, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs
=> L5 agent delegation quickfix

src/Authentication/Controllers/SystemUserController.cs
=> return value

src/Authentication/Controllers/SystemUserController.cs
=> L5 summary fix

src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Integration/AccessManagement/AccessManagementClient.cs, src/Integration/AccessManagement/IAccessManagementClient.cs, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs
=> create return list of extConnection

src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/Problems/Problem.cs, src/Integration/AccessManagement/AccessManagementClient.cs, src/Integration/AccessManagement/IAccessManagementClient.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs
=> add endpoint for deleting agent systemuser

src/Authentication/Controllers/SystemUserController.cs, src/Core/Problems/Problem.cs, src/Integration/AccessManagement/AccessManagementClient.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs
=> updated the endpoint for deleteagent to match AM

src/Authentication/Services/SystemUserService.cs
=> Check for the problem detail and not the object

src/Authentication/Controllers/RequestSystemUserController.cs, src/Authentication/Services/Interfaces/IRequestSystemUser.cs, src/Authentication/Services/RequestSystemUserService.cs, src/Core/Problems/Problem.cs, test/Altinn.Platform.Authentication.Tests/Controllers/RequestControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Mocks/RequestSystemUserServiceMock.cs
=> L5 validate party owns request during approve step

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Core/Errors/ValidationErrors.cs, src/Core/Models/SystemRegisters/RegisteredSystemDTO.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterInvalidResourceIdFormat.json
=> Add validation for resource id attribute

src/Authentication/Services/SystemUserService.cs, src/Core/Models/SystemUsers/ConnectionDto.cs, src/Integration/AccessManagement/AccessManagementClient.cs, src/Integration/AccessManagement/IAccessManagementClient.cs, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs
=> changed response DTO from AM client delegation

test/Altinn.Platform.Authentication.SystemIntegrationTests/Clients/PlatformAuthenticationClient.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Clients/SystemRegisterClient.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Clients/SystemUserClient.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Domain/Testusers.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Resources/Testdata/ClientDelegation/CreateRequest.json, test/Altinn.Platform.Authentication.SystemIntegrationTests/Resources/Testusers/testusers.at22.json, test/Altinn.Platform.Authentication.SystemIntegrationTests/Resources/Testusers/testusers.tt02.json, test/Altinn.Platform.Authentication.SystemIntegrationTests/Tests/ChangeRequestTests.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Tests/ClientDelegation/ClientDelegationTests.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Tests/SystemUserTests.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Utils/ApiEndpoints.cs, test/Altinn.Platform.Authentication.SystemIntegrationTests/Utils/Common.cs, test/Bruno/Altinn.Authentication/VendorRequest/ClientDelegation/CreateRequest/Create System User Request.bru, test/Bruno/Altinn.Authentication/VendorRequest/Systemuser-L2/Create System User Request.bru
=> fixed testdata for e2e tests + new endpoint from BFF for customers

src/Integration/AccessManagement/AccessManagementClient.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Data/Packages/packages.json, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterWithAccessPackageAgent.json, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs
=> added foretningsforer hardcoding

src/Core/Models/Rights/DetailCodeExternal.cs
=> Update the detailcodeexternal to be in sync with AM

src/Authentication/Services/SystemUserService.cs, src/Core/Models/Rights/Customer.cs, src/Core/Models/SystemUsers/AgentDelegationInputDto.cs, src/Integration/AccessManagement/AccessManagementClient.cs
Updated client api to include rolepackages and updated delegation api to use the returned rolepackages instead of hard coding
=> Support for both virksomhetsdelegation and clientdelegation

src/Integration/AccessManagement/AccessManagementClient.cs
=> extract urnvalue for finding the role

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Services/Interfaces/ISystemRegisterService.cs, src/Authentication/Services/SystemRegisterService.cs
=> add detailed validation for access package format failure

src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Program.cs, src/Authentication/ServiceDefaults/AltinnClusterInfo.cs, src/Authentication/ServiceDefaults/ConfigureAltinnClusterInfo.cs, src/Authentication/ServiceDefaults/IPNetworkUtils.cs, src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/Models/SystemUser.cs, src/Core/RepositoryInterfaces/ISystemUserRepository.cs, src/Persistance/RepositoryImplementations/SystemUserRepository.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/appsettings.json
=> Bugfix pagination vendor getsystemuser list

src/Authentication/Configuration/FeatureFlags.cs, src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Authentication/appsettings.json, src/Core/Clients/Interfaces/IPartiesClient.cs, src/Core/Enums/CustomerRoleType.cs, src/Core/Models/SystemUsers/CustomerList.cs, src/Core/Models/SystemUsers/PartyRecord.cs, src/Integration/AccessManagement/AccessManagementClient.cs, src/Integration/AccessManagement/IAccessManagementClient.cs, src/Integration/Clients/PartiesClient.cs, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs, test/Altinn.Platform.Authentication.Tests/Mocks/PartiesClientMock.cs, test/Altinn.Platform.Authentication.Tests/appsettings.json
Added feature flag and customer api mock for fetching and delegation  with register endrpoint
=> Feature flag for mocking customer list

src/Integration/Clients/PartiesClient.cs
=> fix format for urn

src/Integration/Clients/PartiesClient.cs
=> accesstoken

test/Altinn.Platform.Authentication.PerformanceTests/README.md, test/Altinn.Platform.Authentication.PerformanceTests/common/config.js, test/Altinn.Platform.Authentication.PerformanceTests/common/readPartiesQueryData.js, test/Altinn.Platform.Authentication.PerformanceTests/common/readTestdata.js, test/Altinn.Platform.Authentication.PerformanceTests/commonSystemUser.js, test/Altinn.Platform.Authentication.PerformanceTests/createAndConfirmSystemUser.js, test/Altinn.Platform.Authentication.PerformanceTests/createClientDelegations.js, test/Altinn.Platform.Authentication.PerformanceTests/getSystemUser.js, test/Altinn.Platform.Authentication.PerformanceTests/partiesQuery.js
- Refaktorering for å kunne kjøre knekkpunkttester
- Oppdatert readme
=> chore(performance): Refaktorert og oppdatert readme

src/Authentication/Altinn.Platform.Authentication.csproj, src/Authentication/Attributes/DoNotTrimAttribute.cs, src/Authentication/Controllers/ChangeRequestSystemUserController.cs, src/Authentication/Controllers/RequestSystemUserController.cs, src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Filters/TrimStringsActionFilter.cs, src/Authentication/Program.cs, test/Altinn.Platform.Authentication.Tests/Filters/TrimStringActionFilterTests.cs
=> Added filter to trim strings on input objects that are not list or array

src/Authentication/Controllers/SystemChangeLogController.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/SystemChangeLogControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Data/SystemChangeLog/ChangeLogAll.json, test/Altinn.Platform.Authentication.Tests/Helpers/SystemRegisterTestHelper.cs
=> added scope for get for changelog and more tests

src/Authentication/Services/SystemUserService.cs
=> fix validation for rights and accesspackage

src/Integration/AccessManagement/AccessManagementClient.cs
- updated party uuid to system user id
- fix logging text for accessmanagement client
- log validation errors from AM
=> Update guid to party guid for system user for push to AM operation

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Services/Interfaces/ISystemRegisterService.cs, src/Authentication/Services/SystemRegisterService.cs, src/Core/Models/AccessPackages/Package.cs
=> Fix validation of accesspackages in system

src/Authentication/appsettings.json
=> changed page size from 20 to 50

src/Core/Errors/ValidationErrors.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs
=> Update the validation message to match the validation check

src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Services/Interfaces/ISystemUserService.cs, src/Authentication/Services/SystemUserService.cs, src/Core/Models/SystemUsers/StandardSystemUserDelegations.cs, src/Integration/AccessManagement/AccessManagementClient.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Data/Delegation/AccessPackagesForSystemUser.json
=> get delgated accesspackage, rights for et system user

src/Authentication/Services/SystemUserService.cs
=> fix delete system user check

src/Authentication/Services/SystemUserService.cs
=> fromBff fix

src/Authentication/Controllers/SystemRegisterController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Core/Errors/ValidationErrors.cs, test/Altinn.Platform.Authentication.Tests/Altinn.Platform.Authentication.Tests.csproj, test/Altinn.Platform.Authentication.Tests/AuthenticationHelperTests.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemRegisterControllerTests.cs, test/Altinn.Platform.Authentication.Tests/Data/SystemRegister/Json/SystemRegisterInvalidSystemId.json
Add validation for sytemid format with spaces and validation for updating a deleted system
=> Validation for systemid and update a deleted system

src/Authentication/Services/ChangeRequestSystemUserService.cs, src/Authentication/Services/SystemUserService.cs
=> L4 change model fix

src/Authentication/Services/ChangeRequestSystemUserService.cs, src/Authentication/Services/SystemUserService.cs
=> L4 from bff false fix

src/Authentication/Services/ChangeRequestSystemUserService.cs, src/Authentication/Services/SystemUserService.cs
=> L4 false fix delegationcheck

src/Authentication/Controllers/SystemUserClientDelegationController.cs
=> Make the method private that is not exposed outside the controller

src/Authentication/Controllers/SystemUserClientDelegationController.cs, src/Authentication/Controllers/SystemUserController.cs, src/Authentication/Helpers/AuthenticationHelper.cs, src/Authentication/Model/ClientInfo.cs, src/Core/Errors/ValidationErrors.cs, test/Altinn.Platform.Authentication.Tests/Controllers/SystemUserClientDelegationControllerTest.cs, test/Altinn.Platform.Authentication.Tests/Mocks/AccessManagementClientMock.cs, test/Altinn.Platform.Authentication.Tests/Mocks/PartiesClientMock.cs
=> updated client information model and input to addclient

src/Persistance/RepositoryImplementations/SystemRegisterRepository.cs
=> add isdeleted filter to getallregisteredsystemsforvendor
